### ISSUE TITLE
Destroyed invalid prefab

### ISSUE THREAD

**Issue by MSchmoecker** [Valheim-Modding/ValheimLib#5]
There seems to be a timing problem when adding pieces at `ObjectDBHelper.OnAfterInit`. When you use the `InstantiateClone()` extension method, it is added to the `NetworkedModdedPrefabs` list. But `On.ZNetScene.Awake` is called before that, so it is never added to the `m_namedPrefabs` Dictionary.

If you then load a world with a builded piece everything works, until you use a portal. If you get back the console prints "Destroyed invalid prefab ZDO:-918684522:6199830" (not always the same number) and the piece is gone.

I made a hotfix to my pressure plate mod where the item is added right bevore `ZNetScene.Awake` is called. I have not much time at the moment, so maybe you can take a deeper look at this bug.

**Comment by xiaoxiao921** [comment]
Thanks, i'll take a look

**Comment by MSchmoecker** [comment]
Thanks, this fixes the issue. I'm not sure why it isn't interfering with my hotfix but I don't complain :)
