### ISSUE TITLE
DLL version does not match release version

### ISSUE THREAD

**Issue by Fredrik81** [Valheim-Modding/ValheimLib#6]
Please make sure to update DLL version with the release version so it's easier to track what is installed.
Example of current release when creating issue:
Release on github: 0.0.12
Version of DLL file: 1.0.0.0
![image](https://user-images.githubusercontent.com/21292774/111906468-f6f1f180-8a50-11eb-84a8-b3cc7cc72c66.png)

**Comment by xiaoxiao921** [comment]
Thanks, should be fixed for the next release
